"""empty message

Revision ID: 39cbc3c390b4
Revises: 4527aef5d85a
Create Date: 2019-11-14 17:28:59.431484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39cbc3c390b4'
down_revision = '4527aef5d85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('first_crawl',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('NewsURL', sa.String(length=255), nullable=False),
    sa.Column('src', sa.String(length=40), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('second_crawl',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('NewsURL', sa.String(length=255), nullable=False),
    sa.Column('visit_time', sa.Integer(), nullable=False),
    sa.Column('src', sa.String(length=64), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('second_crawl')
    op.drop_table('first_crawl')
    # ### end Alembic commands ###
