"""empty message

Revision ID: 4527aef5d85a
Revises: b600c60b2eec
Create Date: 2019-10-18 13:11:19.779322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4527aef5d85a'
down_revision = 'b600c60b2eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('second_crawl',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('NewsURL', sa.String(length=255), nullable=False),
    sa.Column('visit_time', sa.Integer(), nullable=False),
    sa.Column('src', sa.String(length=64), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('second_crawl')
    # ### end Alembic commands ###
