"""empty message

Revision ID: bfa4b85ee6d2
Revises: 
Create Date: 2019-10-18 09:46:25.902937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa4b85ee6d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('first_crawl',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('NewsURL', sa.String(length=255), nullable=False),
    sa.Column('src', sa.String(length=40), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('second_crawl',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('NewsURL', sa.String(length=255), nullable=False),
    sa.Column('visit_time', sa.Integer(), nullable=False),
    sa.Column('src', sa.String(length=64), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('second_crawl')
    op.drop_table('first_crawl')
    # ### end Alembic commands ###
