"""empty message

Revision ID: cd7b0b16113e
Revises: bfa4b85ee6d2
Create Date: 2019-10-18 12:46:10.809139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7b0b16113e'
down_revision = 'bfa4b85ee6d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('first_crawl',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('NewsURL', sa.String(length=255), nullable=False),
    sa.Column('src', sa.String(length=40), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('first_crawl')
    # ### end Alembic commands ###
